### ISSUE TITLE
A possible minor hardening idea

### ISSUE THREAD

**Issue by 1082008** [dominictarr/secret-handshake-paper#10]
The original protocol flows like this:

1. ? &rarr; ?: a<sub>p</sub>, hmac<sub>K</sub>(a<sub>p</sub>)
2. ? &larr; ?: b<sub>p</sub>, hmac<sub>[K|a·b]</sub>(b<sub>p</sub>)
3. H = A<sub>p</sub>|Sign<sub>A</sub>(K|B<sub>p</sub>|hash(a·b))
   A &rarr; B: Box<sub>[K|a·b|a·B]</sub>(H)
4. A &larr; B: Box<sub>[K|a·b|a·B|A·b]</sub>(Sign<sub>B</sub>(K|H|hash(a·b)))

Assuming K is public, every attacker can proceed with the first two steps. Obviously the attacker won't be able to create a valid Auth message without knowing A<sub>p</sub> and B<sub>p</sub>, but why do we let him get so far?

My idea is that B<sub>p</sub> can be included in the hmac key:

1. ? &rarr; ?: a<sub>p</sub>, hmac<sub>[K|B<sub>p</sub>]</sub>(a<sub>p</sub>)
2. ? &larr; ?: b<sub>p</sub>, hmac<sub>[K|B<sub>p</sub>|a·b]</sub>(b<sub>p</sub>)
3. H = A<sub>p</sub>|Sign<sub>A</sub>(K|B<sub>p</sub>|hash(a·b))
   A &rarr; B: Box<sub>[K|a·b|a·B]</sub>(H)
4. A &larr; B: Box<sub>[K|a·b|a·B|A·b]</sub>(Sign<sub>B</sub>(K|H|hash(a·b)))

(We could use a·B instead of B<sub>p</sub> but validation would use more resources on the server side.)

I don't see any weeknesses in the protocol this change would cause.

**Comment by dominictarr** [comment]
that would certainly harden to one kind of attack, but on the other hand, it would mean that a replay attacker that as observed a connection between A and B, can confirm that B has moved to a new address but is using the same key.

Lets say B moves house, and now has a different ip address, the attacker can then replay the `a_p, hmac[k|B_p](a_p)` A sent to B before, and if B responds, the attacker knows this is now B's address.

**Comment by 1082008** [comment]
I see. This is the same problem as the first one of CurveCP's according to the paper. Thanks!
